development: &default
  username: yonah.forst-facilitator_api1.gmail.com
  password: JKRY6A97TM9B7RMB
  signature: AGQhREreiii3y8lq1rbSiVxcO5gHAjxEcP2oAUtUhXsII0z9jUxy4KWg
  app_id: APP-80W284485P519543T
  http_timeout: 30
  mode: sandbox
  sandbox_email_address: yonah.forst@gmail.com
  # # with certificate
  # cert_path: "config/cert_key.pem"
  # # with token authentication
  # token: ESTy2hio5WJQo1iixkH29I53RJxaS0Gvno1A6.YQXZgktxbY4I2Tdg
  # token_secret: ZKPhUYuwJwYsfWdzorozWO2U9pI
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with device ip address
  # device_ipaddress: "127.0.0.1"
test:
  <<: *default
production:
  mode: live
  username: USERNAME
  password: PASSWORD
  signature: SIGNATURE
  app_id: APP_ID
  
  
  
  
  
  # PayPal::SDK.configure(
  #   :mode      => "sandbox",  # Set "live" for production
  #   :app_id    => "APP-80W284485P519543T",
  #   :username  => "yonah.forst-facilitator_api1.gmail.com",
  #   :password  => "JKRY6A97TM9B7RMB",
  #   :signature => "AGQhREreiii3y8lq1rbSiVxcO5gHAjxEcP2oAUtUhXsII0z9jUxy4KWg" )
  #
  # @api = PayPal::SDK::AdaptivePayments.new
  #
  # @pay = @api.build_pay({
  #   :actionType => "PAY",
  #   :cancelUrl => "http://localhost:3000/samples/adaptive_payments/pay",
  #   :currencyCode => "USD",
  #   :feesPayer => "EACHRECEIVER",
  #   :ipnNotificationUrl => "http://localhost:3000/samples/adaptive_payments/ipn_notify",
  #   :receiverList => {
  #     :receiver => [{
  #       :amount => 1.0,
  #       :email => "chris@vetula.com" }] },
  #   :returnUrl => "http://localhost:3000/samples/adaptive_payments/pay" })
  #
  #   @response = @api.pay(@pay)
  #